version: '3'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - docker_ojs
    restart: unless-stopped
  
  postgres:
    image: postgres
    volumes:
      - /postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks: 
      - docker_ojs
    restart: unless-stopped

networks:
  docker_ojs:
    driver: bridge