version: '3'

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    networks:
      - docker_ojs
    restart: unless-stopped
  
  postgres:
    image: postgres
    environment: 
    - POSTGRES_PASSWORD=ojs
    - POSTGRES_USER = ojs
    - POSTGRES_DB = ojs

    ports:
      - "5432:5432"
    networks: 
      - docker_ojs
    restart: unless-stopped

networks:
  docker_ojs:
    driver: bridge